{
     "emp_fullname": "shubham vishwakarma",    
     "emp_phone_no": "9898989898",    
     "emp_state":"M.p.",    
     "emp_city": "Indore",    
     "emp_hotel": "hotelx",    
      "emp_social_security":"rfrfe",
      "emp_date": "20/11/2023",    
      "employee_address":"TBD",    
      "emp_gender": "Male",    
      "emp_postal_code":"452001",    
      "emp_civil_status":"defe",    
      "emp_degree":"fdsfds",    
      "emp_hire_date":"fdfdf",    
      "emp_salary":"20000",    
      "emp_average_hours_per_week":"40",    
      "emp_position_title_second_job":"fdfsf",    
      "emp_company_name" :"saviesa",    
      "emp_responsibility" :"dfefde",    
      "emp_incident_details" :"cdced",   
      "emp_incident_date":"12/12/2023",    
      "emp_today_date" :"20/11/2023",    
      "emp_incident_time":"10:30" ,    
      "emp_start_time_shift":"04:50" ,    
      "emp_workers_compensation_claims":"ccsd",    
      "supervisor_state" :"mp",    
      "supervisor_city":"indore",    
      "supervisor_hotel" :"hotel radha krishna",    
      "supervisor_postal_code":"452001" ,    
      "supervisor_name" :"piyus",    
      "supervisor_phone_no":"58689586" ,     
      "injured_part":"left hand",     
      "damage":"yes",     
      "claim_questionable":"df",    
      "claim_answer":"fds" ,     
      "medical_center_state":"mp",    
      "medical_center_city" :"indore",     
      "medical_center_postel_code":"3434234234",     
      "medical_center_name":"MY",     
      "representative_name":"chandransh",     
      "suit":"defde",
}